### ISSUE TITLE
nv环境 readme 报 CUDA_ERROR_UNSUPPORTED_PTX_VERSION 后应该怎么做？

### ISSUE THREAD

**Issue by Aganlengzi** [InfiniTensor/InfiniLM#23]
RT
env:
```
root@0dea5388ce98:/workspace/InfiniLM# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |

```
command & output
```
root@0dea5388ce98:/workspace/InfiniLM# RUST_BACKTRACE=1 cargo chat --model TinyLlama-1.1B-Chat-v1.0_f16 --turbo nv:7
    Finished `release` profile [optimized] target(s) in 0.13s
     Running `target/release/xtask chat --model TinyLlama-1.1B-Chat-v1.0_f16 --turbo 'nv:7'`
thread '<unnamed>' panicked at /root/.cargo/git/checkouts/cuda-driver-05ca9b11fbfadbb6/d089ada/cuda/src/nvrtc/module.rs:12:9:
assertion `left == right` failed
  left: CUDA_ERROR_UNSUPPORTED_PTX_VERSION
 right: CUDA_SUCCESS
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: operators::handle::nvidia_gpu::module::ModuleBox::share
   5: operators::handle::nvidia_gpu::Internal::compile_kernel
   6: <operators::rms_norm::nvidia_gpu::Operator as common::Operator>::scheme
   7: common_nv::Internal::new
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   9: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
  10: common_nv::NvidiaKernels::new
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /workspace/InfiniLM/models/llama/nvidia-gpu/src/lib.rs:124:42:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: service::Service<M>::load
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::runtime::Runtime::block_on
   6: xtask::Task::run
   7: xtask::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /root/.cargo/git/checkouts/cuda-driver-05ca9b11fbfadbb6/d089ada/cuda/src/dev_mem.rs:64:1:
internal error: entered unreachable code: Never drop ContextSpore
stack backtrace:
   0:     0x5555559f9c0a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x555555a24eab - core::fmt::write::hf5713710ce10ff22
   2:     0x5555559f66c3 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x5555559faef2 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x5555559fab5e - std::panicking::default_hook::h81c8cd2e7c59ee33
   5:     0x5555559fb77f - std::panicking::rust_panic_with_hook::had2118629c312a4a
   6:     0x5555559fb433 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   7:     0x5555559fa0e9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   8:     0x5555559fb0f4 - rust_begin_unwind
   9:     0x5555555dd1f3 - core::panicking::panic_fmt::h3eea515d05f7a35e
  10:     0x5555557028c2 - core::ptr::drop_in_place<tensor::tensor::Tensor<cuda::dev_mem::DevMemSpore>>::ha780f4244d61eda8
  11:     0x55555570a331 - service::Service<M>::load::ha44bfafab9333253
  12:     0x55555566f859 - tokio::runtime::park::CachedParkThread::block_on::hb38ed19627a77ecc
  13:     0x555555611af9 - tokio::runtime::runtime::Runtime::block_on::hc300cd9b7a431abb
  14:     0x5555556cf5e8 - xtask::Task::run::hcd4c9d83ec232ec5
  15:     0x55555570fc2b - xtask::main::h567dc4f3dc0cd393
  16:     0x5555556b4383 - std::sys::backtrace::__rust_begin_short_backtrace::h2ed3d6e83d11c17d
  17:     0x5555556f8879 - std::rt::lang_start::{{closure}}::h639538c8785efc01
  18:     0x5555559ee9e0 - std::rt::lang_start_internal::h4d90db0530245041
  19:     0x555555717ce5 - main
  20:     0x7fffbf200d90 - <unknown>
  21:     0x7fffbf200e40 - __libc_start_main
  22:     0x5555555ddac5 - _start
  23:                0x0 - <unknown>
thread 'main' panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
root@0dea5388ce98:/workspace/InfiniLM#
```

**Comment by YdrMaster** [comment]
不是很理解，正常来说是不可能报这个错的，因为这个 ptx 是原地编译出来的，它用的各种 version 也是当场通过驱动获取的
